import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import ProfilePic from "../../public/images/profile/developer-pic-2.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import LightBuld from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>Drey Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light  ">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 bg-light rounded-full overflow-hidden md:w-full">
              <Image
                src={ProfilePic}
                alt="Drey"
                className="w-full h-auto dark:bg-dark lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw,
                (max-with: 1200px) 50vw,
                33vw"
              />
            </div>

            <div className="w-1/2 flex flex-col items-center self-center lg:w-full">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl text-left 
                xl:!text-5xl lg:!txet-center lg:!text-6xl md:!text-5xl sm:!text-3xl lg:text-center
                "
              />
              <p className="my-4 text-base font-medium md:text-sm sm:text-xs">
                As a skilled front-end developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects, showcasing my expertise in React.js,React-Native and
                web development.
              </p>

              <div className="flex items-center self-start mt-2 lg:self-center ">
                <Link
                  href="/Resume.pdf"
                  target={"_blank"}
                  download={true}
                  className="flex items-center bg-dark hover:dark:bg-dark hover:dark:text-
                   dark:bg-light dark:text-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                    hover:bg-light hover:text-dark border-2 border-transparent hover:border-dark
                     hover:dark:border-light hover:dark:text-light md:p-2 md:px-4 md:text-base "
                >
                  Resume <LinkArrow className={"w-6 m-1 h-6"} />
                </Link>

                <Link
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                  href="mailto:adebisidrey@gmail.com"
                  target={"_blank"}
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image src={LightBuld} alt="drey" className="w-full h-auto" />
        </div>
      </main>
    </>
  );
}
